### ISSUE TITLE
Able to move the piece along the bottom forever

### ISSUE THREAD

**Issue by fppt** [aelred/tetris#2]
If I move a piece left and right when it hits the bottom I am able to continuously move it about just by tapping between left and right. 

This bug is truly horrendous! I have no idea how it ever snuck past QA. I recommend you revaluate you TDD/BDD/DDD approaches @aelred. Truly shameful

**Comment by aelred** [comment]
lol ok

**Comment by aelred** [comment]
I've been working on resolving this issue nonstop since you brought it to my attention in January. After 10 months of hard work and a lot of personal introspection, I finally implemented the feature:

http://tetris.ael.red/?args=for-filipe

**Comment by fppt** [comment]
I must say I was starting to lose faith in this CRITICAL issue getting resolved. My hope for the project has been restored.
